#
#   Permission: shiftclick.use
#

messages:
  prefix: "&6ShiftClick &8>&r "
  no_permission: "&cYou don't have permission to do this"

config:
  #Cooldown in ticks
  cooldown: 60

  #Add or remove worlds
  enabled_worlds:
    - minecraft:overworld
    - minecraft:the_nether
    - minecraft:the_end

  #You can use variable %player_clicker% and %player_clicked%
  commands:
    - command1
    - command2
