#
#   Permission: shiftclick.use
#

messages:
  prefix: "&6ShiftClick &8>&r "
  no_permission: "&cYou don't have permission to do this"

config:
  #Cooldown in ticks
  cooldown: 60

  #Add or remove worlds
  enabled_worlds:
    - minecraft:overworld
    - minecraft:the_nether
    - minecraft:the_end

  #Commands executed by the server
  #You can use variable %player_clicker% and %player_clicked%
  server_ commands:
    - server1
    - server2
  #Commands executed by the player
  #You can use variable %player_clicker% and %player_clicked%
  player_ commands:
    - player1
    - player2